springfox.documentation.swagger.v2.path: /oai/api-docs
spring:
   cloud:
      stream:
         bindings:
            products:
               destination: productsTopic
               content-type: application/json
               group: report-factory
            orders:
               destination: ordersTopic
               content-type: application/json
               group: report-factory
            statusUpdates:
               destination: statusUpdatesTopic
               content-type: application/json
               group: report-factory
            rabbit:
               binder:
                  nodes: rabbitmq
                  adminAddresses: rabbitmq