springfox.documentation.swagger.v2.path: /oai/api-docs
spring:
   rabbitmq:
      addresses: rabbitmq
   cloud:
      stream:
         bindings:
            products:
               destination: productsTopic
               content-type: application/json
               group: report-factory
            orders:
               destination: ordersTopic
               content-type: application/json
               group: report-factory
            statusUpdates:
               destination: statusUpdatesTopic
               content-type: application/json
               group: report-factory
            rabbit:
               binder:
                  nodes: rabbitmq
                  adminAddresses: rabbitmq
security:
   oauth2:
      resource:
         userInfoUri: http://identity-service:8080/user